config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :customers, controllers: {
  	sessions:      'customers/sessions',
  	passwords:     'customers/passwords',
  	registrations: 'customers/registrations'
  }

  root 'home#top'
  get 'customers/about' => 'customers/home#about' #abouotページ
  get 'customers/contact' => 'customers/contacts#contact' #問合せフォーム
  post 'customers/confirm' => 'customers/contacts#confirm' #問合せ内容確認画面
  post 'customers/thanks' => 'customers/contacts#thanks' #問合せありがとうページ

  get 'customers/mypage' => 'customers#mypage' #myページ
  get 'customers/edit' => 'customers#edit' #パスワード編集ページ
  get 'customers/fix' => 'customers#fix' #編集ページ
  patch 'customers/fix' => 'customers#fix_update'
  put 'customers/fix' => 'customers#fix_update'
  get 'customers/withdraw' => 'customers#withdraw' #退会ページ
  put 'customers/withdraw' => 'customers#withdraw_update'

  get 'customers/cafe_posts/favorite' => 'customers/cafe_posts#favorite' #猫カフェ投稿いいね一覧
  get 'customers/product_posts/favorite' => 'customers/product_posts#favorite' #猫グッズ投稿いいね

  get 'customers/product_posts/mypost' => 'customers/product_posts#mypost' #自分の投稿
  get 'customers/product_posts/posts' => 'customers/product_posts#posts' #@customerの投稿

  post 'follow/:id' => 'customers/relationships#follow', as: 'follow' #フォローする
  delete 'unfollow/:id' => 'customers/relationships#unfollow', as: 'unfollow' #フォローを外す

# 　resources :customers, only: [:show, :index, :edit, :update] #フォロー
  get 'customers/:customer_id/followers' => 'customers/relationships#followers', as: 'followers'
  get 'customers/:customer_id/follows' => 'customers/relationships#follows', as: 'follows'

  get 'customers/search' => 'customers/product_posts#search' #postのsearch

  get 'customers/product_categories' => 'customers/product_categories#index' #カテゴリー一覧



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :customers do
  	resources :cafe_posts, only: [:index, :show, :update, :edit, :destroy, :create, :new] do #猫カフェ投稿
  	  resources :cafe_comments, only: [:create, :destroy] #猫カフェコメント
  	  resource :cafe_favorites, only: [:create, :destroy] #猫カフェいいね
  	end

  	resources :product_posts, only: [:index, :show, :update, :edit, :destroy, :create, :new] do #猫グッズ投稿
  	  resources :product_comments, only: [:create, :destroy] #猫グッズコメント
  	  resource :product_favorites, only: [:create, :destroy] #猫グッズいいね 
  	end

  end

end

app/controllers/customers/cafe_categories_controller.rb
class Customers::CafeCategoriesController < ApplicationController
end

app/controllers/customers/cafe_comments_controller.rb
class Customers::CafeCommentsController < ApplicationController

  before_action :authenticate_customer! #ログインしているユーザーのみ入れる

 def create
  @cafe_post = CafePost.find(params[:cafe_post_id])
  @cafe_comment = current_customer.cafe_comments.new(cafe_comment_params)
  @cafe_comment.cafe_post_id = @cafe_post.id
  if !@cafe_comment.comment_already_posted? && @cafe_comment.save
  	flash[:notice] = "success!"
  	redirect_to request.referer #成功
  else
    @customer = @cafe_post.customer
    @comments = CafeComment.where(cafe_post_id: @cafe_post.id).page(1).per(5)
  	render 'customers/cafe_posts/show' #失敗
  end
 end

 def destroy
  comment = CafeComment.find(params[:id])
  comment.destroy
  redirect_back(fallback_location: root_path)
 end

 private
 def cafe_comment_params
 	params.require(:cafe_comment).permit(:comment, :customer_id, :cafe_post_id, :total_rate)
 end
end

app/controllers/customers/cafe_favorites_controller.rb
class Customers::CafeFavoritesController < ApplicationController

  before_action :authenticate_customer! #ログインしエチルユーザーのみ

  def create
  @cafe_post = CafePost.find(params[:cafe_post_id])
  favorite = current_customer.cafe_favorites.new(cafe_post_id: @cafe_post.id)
  favorite.save
  redirect_to customers_cafe_post_path(@cafe_post)
 end

 def destroy
  @cafe_post = CafePost.find(params[:cafe_post_id])
  favorite = current_customer.cafe_favorites.find_by(cafe_post_id: @cafe_post.id)
  favorite.destroy
  redirect_to customers_cafe_post_path(@cafe_post)
 end

end

app/controllers/customers/cafe_posts_controller.rb
class Customers::CafePostsController < ApplicationController

  before_action :authenticate_customer! #ログインしているユーザーのみ入れる

 def index
  @cafe_post = CafePost.new
  @cafe_posts = CafePost.all.page(params[:page]).per(8) #paginate
 end

 def show
  @cafe_post = CafePost.find(params[:id])
  @cafe_comment = CafeComment.new #コメントの投稿
  @customer = @cafe_post.customer
  @comments = CafeComment.where(cafe_post_id: @cafe_post.id).page(params[:page] || 1).per(5)
 end

 def favorite
  @cafe_posts = current_customer.favorite_cafes.page(params[:page]).per(8)
 end

 def create
 	@cafe_post = CafePost.new(cafe_post_params)
 	@cafe_post.customer_id = current_customer.id
 	if @cafe_post.save
 		  redirect_to customers_cafe_post_path(@cafe_post.id)
 	else
 		  render :new
 	end
 end

 def new
 	@cafe_post = CafePost.new
 end

 def destroy
  cafe_post = CafePost.find(params[:id])
  cafe_post.destroy
  redirect_to customers_cafe_posts_path
 end

 def edit
 	@cafe_post = CafePost.find(params[:id])
 end

 def update
 	@cafe_post = CafePost.find(params[:id])
 	if @cafe_post.update(cafe_post_params)
 		 redirect_to customers_cafe_posts_path(@cafe_post.id)
 	else
 		 render :edit
 	end
 end

 private

 def cafe_post_params
  params.require(:cafe_post).permit(:customer_id, :cafe_category_id, :price_rate, :free_rate, :total_rate, :shop_name, :price, :description, :picture, :name)
 end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/contacts_controller.rb
class Customers::ContactsController < ApplicationController

  before_action :authenticate_customer! #ログインしているユーザーのみ入れる

 def contact #入力画面を表示
 @contact = Contact.new
 end

 def confirm #入力値のチェック
 @contact = current_customer.contact.build(contact_params)

 if @contact.valid?
 	#OK-確認画面を表示
 	render :action => "confirm"
 else
 	#NG-入力画面を再表示
 	render :action => "contact"
 end
end

 def thanks #送信完了ページ
 @contact = Contact.new(contact_params)
 @contact.customer_id = current_customer.id
 if params[:back]
 	render :action => "contact"
 else
 	@contact.save!
 	render :action => "thanks"
 end
end

 private
 def contact_params
 	params.require(:contact).permit(:contact_name, :contact_email, :contact_content)
 end
end

app/controllers/customers/home_controller.rb
class Customers::HomeController < ApplicationController

 def top
 end

 def about
 end

end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/product_categories_controller.rb
class Customers::ProductCategoriesController < ApplicationController

 def index
  id = params[:id] ? params[:id] : 1

  set_product(id) if params[:type] == ProductCategory.name
  set_cafe(id) if params[:type] == CafeCategory.name
  if params[:type].nil?
  	set_product(id)
    set_cafe(id)
    @mixed_posts = @product_posts + @cafe_posts
  end

  @mixed_posts.sort{|f,s| f.created_at <=> s.created_at}
 end

private

  def set_product(id)
    @product_category = ProductCategory.find(id)
    @mixed_category = @product_category
    @mixed_posts = ProductPost.where(product_category_id: id)
  end

  def set_cafe(id)
    @cafe_category = CafeCategory.find(id)
    @mixed_category = @cafe_category
    @mixed_posts = CafePost.where(cafe_category_id: id)
  end

end

app/controllers/customers/product_comments_controller.rb
class Customers::ProductCommentsController < ApplicationController

 before_action :authenticate_customer! #ログインしエチルユーザーのみ

 def create
  @product_post = ProductPost.find(params[:product_post_id])
  @product_comment = current_customer.product_comments.new(product_comment_params)
  @product_comment.product_post_id = @product_post.id
  if !@product_comment.comment_already_posted? && @product_comment.save
  	redirect_to request.referer #成功
  else
    @customer = @product_post.customer
    @comments = ProductComment.where(product_post_id: @product_post.id).page(1).per(5)
  	render 'customers/product_posts/show' #失敗
  end
 end

 def destroy
  comment = ProductComment.find(params[:id])
  comment.destroy
  redirect_back(fallback_location: root_path)
 end

 private
 def product_comment_params
 	params.require(:product_comment).permit(:comment, :customer_id, :product_post_id, :total_rate)
 end
end

app/controllers/customers/product_favorites_controller.rb
class Customers::ProductFavoritesController < ApplicationController

  before_action :authenticate_customer! #ログインしエチルユーザーのみ

 def create
  @product_post = ProductPost.find(params[:product_post_id])
  favorite = current_customer.product_favorites.new(product_post_id: @product_post.id)
  favorite.save
  redirect_to customers_product_post_path(@product_post)
 end

 def destroy
  @product_post = ProductPost.find(params[:product_post_id])
  favorite = current_customer.product_favorites.find_by(product_post_id: @product_post.id)
  favorite.destroy
  redirect_to customers_product_post_path(@product_post)
 end

end

app/controllers/customers/product_posts_controller.rb
class Customers::ProductPostsController < ApplicationController

  before_action :authenticate_customer! #ログインしているユーザーのみ入れる

 def index
  @product_post = ProductPost.new
  @product_posts = ProductPost.all.page(params[:page]).per(8) #paginate
  @product_categories = ProductCategory.where(is_valid: true)
 end

 def show
  @product_post = ProductPost.find(params[:id])
  @product_comment = ProductComment.new #コメントの投稿
  @customer = @product_post.customer
  @comments = ProductComment.where(product_post_id: @product_post.id).page(params[:page] || 1).per(5)
 end

 def favorite
  @product_posts = current_customer.favorite_products.page(params[:page]).per(8)
 end

 def create
 	@product_post = ProductPost.new(product_post_params)
 	@product_post.customer_id = current_customer.id
 	if @product_post.save
 		  redirect_to customers_product_post_path(@product_post.id)
 	else
 		  render :new
 		end
 end

 def new
 	@product_post = ProductPost.new
 end

 def destroy
  product_post = ProductPost.find(params[:id])
  product_post.destroy
  redirect_to customers_product_posts_path
 end

 def edit
 	@product_post = ProductPost.find(params[:id])
 end

 def update
 	@product_post = ProductPost.find(params[:id])
 	if @product_post.update(product_post_params)
 		 redirect_to customers_product_posts_path(@product_post.id)
 	else
 		 render :edit
 	end
 end

 def mypost
  product_posts = current_customer.product_posts
  cafe_posts = current_customer.cafe_posts
  @mixed_posts = product_posts + cafe_posts
  @mixed_posts.sort{|f,s| f.created_at <=> s.created_at}
 end

 def posts
  @customer = Customer.find(params[:customer_id])
  product_posts = @customer.product_posts
  cafe_posts = @customer.cafe_posts
  @mixed_posts = product_posts + cafe_posts
  @mixed_posts.sort{|f,s| f.created_at <=> s.created_at}
 end

  def search
    @product_post_or_cafe_post = params[:option]
    if @product_post_or_cafe_post == "1"
      @product_posts = ProductPost.search(params[:search], @product_post_or_cafe_post)
    else
      @cafe_posts = CafePost.search(params[:search], @product_post_or_cafe_post)
    end
  end


 private

 def product_post_params
  params.require(:product_post).permit(:customer_id, :product_category_id, :price_rate, :favorite_rate, :total_rate, :product_name, :price, :description, :picture, :name)
 end

end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

   protected

    def after_update_path_for(resource)
     customers_mypage_path
    end
end

app/controllers/customers/relationships_controller.rb
class Customers::RelationshipsController < ApplicationController

  before_action :authenticate_customer! #ログインしエチルユーザーのみ

	def follow
	 current_customer.follow(params[:id])
	 redirect_back(fallback_location: root_path)
	end

	def unfollow
	 current_customer.unfollow(params[:id])
	 redirect_back(fallback_location: root_path)
	end

	def create
	 @customer = Customer.find(params[:relationship][:following_id])
	 current_customer.follow!(@customer)
	 redirect_to @customer
	end

	def destroy
	 @customer = Relationship.find(params[:id]).following
	 current_customer.unfollow!(@customer)
	 redirect_to @customer
	end

  def followers
   @customer = Customer.find(params[:customer_id])
   @customers = @customer.follower_customer
  end

  def follows
   @customer = Customer.find(params[:customer_id])
   @customers = @customer.following_customer
  end

  private
  def create_params
  	params.permit(:following_id).merge(follower_id: current_customer.id)
  end
end

app/controllers/customers/searches_controller.rb
class Customers::SearchesController < ApplicationController

  before_action :authenticate_customer! #ログインしエチルユーザーのみ

  def search
  method = params[:search_method]
  word = params[:search]
  @product_post = ProductPost.search(method, word)
  @cafe_post = CafePost.search(method, word)
 end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  before_action :reject_user, only: [:create]
  #before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected


   def reject_user
     @user = Customer.find_by(email: params[:customer][:email].downcase)
     if @user
       if @user.status == false
         flash[:error] = "退会済みです。"
         redirect_to new_customer_session_path
       end
     else
       flash[:error] = "必須項目を入力してください。"
     end
   end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/views/customers/product_posts/favorite.html.erb
<div class="container">
	<div class="row">

		<%= render 'layouts/sidebar' %>


	     <div class="col-10">

	     	   <%= image_tag("favorite2.jpg", size:'400x80') %>
	     	   <p><%= link_to "全#{@product_posts.count}件" %></p>

         <div class="row">

	         	<% @product_posts.each do |product_post| %>

	     	 <div class="col-3">
	     	 	
           <%= link_to customers_product_post_path(product_post.id) do %>
           <%= image_tag product_post.picture.to_s, size:"150x150" %>
       		  <!-- 商品画像 -->
           <div class="index_title">
       		 <p class="index_product_name">商品名：<%= product_post.product_name %></p> <!-- 商品名 -->

       		 <% end %>

       		 <!-- 評価 -->
       		 <p class="index_total">総合：</p>
       		 <div id="star3-total_rate-<%= product_post.id %>"></div> <!-- 評価 -->
       		</div>
       		   <script>
       		   	$('#star3-total_rate-<%= product_post.id %>').raty({
		           	size    : 36,
		            starOff: '<%= asset_path('star-off.png') %>',
		            starOn : '<%= asset_path('star-on.png') %>',
		            starHalf: '<%= asset_path('star-half.png') %>',
		            scoreName: 'product_post[total_rate]',
		            readOnly: true,
		            half: true,
		            score: <%= product_post.total_rate %>,
               });
       		   </script>

                                        <!-- いいね数とコメント数 -->
              <div class="index_favorite">

               <% if product_post.favorited_by?(current_customer) %>
              <%= link_to customers_product_post_product_favorites_path(product_post), method: :delete do %>
              <p class="good2">　<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
              <%= product_post.product_favorites.count %></p>
            <div class="index_comment">
              <%= link_to " #{product_post.product_comments.count}", customers_product_post_path(product_post.id), class:"fa fa-commenting-o" %>
            </div>
              <% end %>
          <% else %>
              <%= link_to customers_product_post_product_favorites_path(product_post), method: :post do %>
              <p class="good2">　<i class="fa fa-heart-o" aria-hidden="true"></i>
              <%= product_post.product_favorites.count %></p>
            <div class="index_comment">
              <%= link_to " #{product_post.product_comments.count}", customers_product_post_path(product_post.id), class:"fa fa-commenting-o" %>
            </div>
              <% end %>
          <% end %>

             </div>

          　　　<!-- いいね数とコメント -->

          </div>
       	 <% end %>
        
           <div class="page">
       	   <%= paginate @product_posts %>
          </div>


	     	 </div>

	     </div>
	  </div>
  </div>
</div>

app/views/customers/product_posts/show.html.erb
<div class="container">
	<div class="row">

		<%= render 'layouts/sidebar' %>

   <div class="col-10">

    <h3 class="title">猫グッズ詳細<i class="fas fa-cat"></i></h3>
    <%= link_to @product_post_path do %>
    <% end %>

    <p class="product_image">
      <%= image_tag @product_post.picture.to_s, size:"330x330" %>
    </p>

    <div class="product_form">

      <!-- いいね機能 -->

      <% if @product_post.favorited_by?(current_customer) %>
      <%= link_to customers_product_post_product_favorites_path(@product_post), method: :delete do %>
      <p class="good1">　<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
        <%= @product_post.product_favorites.count %></p>
        <% end %>
        <% else %>
        <%= link_to customers_product_post_product_favorites_path(@product_post), method: :post do %>
        <p class="good1">　<i class="fa fa-heart-o" aria-hidden="true"></i>
          <%= @product_post.product_favorites.count %></p>
          <% end %>
          <% end %>

          <p class="product_name good">商品名：<%= @product_post.product_name %></p>
          <p class="product_price good">　価格：<%= @product_post.price %>円</p><br>


          <!-- いいね機能ここまで -->
          <!-- 評価 -->

          <p class="show_title">　　　価格：</p>
          <div id="star1-price_rate-<%= @product_post.id %>"></div><br>

          <p class="show_title">お気に入り：</p>
          <div id="star2-favorite_rate-<%= @product_post.id %>"></div><br>

          <p class="show_title">　　　総合：</p>
          <div id="star3-total_rate-<%= @product_post.id %>"></div><br>

        </div>

        <div class="product_description">

         <br><p class="show_title">説明：</p>
         <%= @product_post.description %><br>

         　　　　　　<!-- 編集・削除ボタン -->

         <% if @product_post.customer_id == current_customer.id %>
         <br><p><%= link_to "編集する", edit_customers_product_post_path(@product_post), class:"button" %>
           <%= link_to "削除する", @product_post_path, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "button destroy_product_post_#{@product_post.id}" %></p>
           <% end %>

           <!-- 編集・削除ボタンここまで -->

           <!-- 投稿者の情報 -->

           <div class="post_customer">
            <p class="post_customer_name_image">
              投稿者：<%= @product_post.customer.name %>
              <%= image_tag @product_post.customer.profile_image.to_s, size:"100x100" %>
            </p>

            <div class="post_customer_name_image follow">
              <p><i class="fas fa-flag"></i><%= "フォロー数: #{@customer.follower.count}" %> <i class="fa fa-heart"></i><%= "フォロワー数: #{@customer.followed.count}" %></p>
              <td>
              </div>

              <div class="show_button">
                <% unless @customer == current_customer %>
                <% if current_customer.following?(@customer) %>
                <p><%= link_to 'フォロー外す', unfollow_path(@customer.id), method: :DELETE, class: "button red" %>
                  <% else %>
                  <%= link_to 'フォローする', follow_path(@customer.id), method: :POST, class: "button" %></p>
                  <% end %>
                  <% end %>

                </div>

              </div>

              <!-- 投稿者の情報ここまで -->

              <!-- コメント表示 -->

              <br><h3 class="comment_customer">コメント</h3>

              <div class="comment_customer">
                <% @comments.each do |product_comment| %>
                <div class="comment">
                  <div class="comment-body">

                    <div class="profile_image">
                     <%= image_tag product_comment.customer.profile_image.to_s, size:"60x60" %>
                     <%= product_comment.customer.name %>
                   </div>

                   <div class="comment-text">

                    <p class="show_title">総合：</p>
                    <div id="star4-total_rate-<%= product_comment.id %>"></div><br> <!-- コメント星レビュー -->

                    <script>
                      $('#star4-total_rate-<%= product_comment.id %>').raty({
                        size    : 36,
                        starOff: '<%= asset_path('star-off.png') %>',
                        starOn : '<%= asset_path('star-on.png') %>',
                        starHalf: '<%= asset_path('star-half.png') %>',
                        scoreName: 'product_comment[total_rate]',
                        readOnly: true,
                        half: true,
                        score: <%= product_comment.total_rate %>,
                      });
                    </script>

                    <%= product_comment.comment %>

                    <% if product_comment.customer == current_customer %>
                    <%= link_to '', customers_product_post_product_comment_path(@product_post,product_comment), method: :delete, class:"fas fa-trash fa trash_black" %>
                    <% end %>
                  </div>
                </div>
                <%=  image_tag("line.jpg", size:'530x65') %>
              </div>
              <% end %>
            </div>
            <%= paginate @comments %>
            <!-- コメント表示ここまで -->
            <!-- コメントフォーム -->
            <%= form_for [@product_post, @product_comment], url:customers_product_post_product_comments_path(@product_post) do |f| %>
            <div class="comment_form">
             <div class="col-6">

              <div class="form_group row" id="star4">
                <%= f.label :total_rate, '総合', class:"col-md-4 col-form-label" %>
                <%= f.hidden_field :total_rate, id: :review_star %>
              </div>

              <%= f.text_area :comment,row:'3', class: "form-control",placeholder:"コメントここに" %>
            </div>
            <%= f.submit "投稿する", class:"button" %>
            <% end %>
          </div><br>
          <!-- コメントフォームここまで -->
          <!-- レビューのscript -->
          <script>
           $('#star1-price_rate-<%= @product_post.id %>').raty({
           	size    : 36,
            starOff: '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            scoreName: 'product_post[price_rate]',
            readOnly: true,
            half: true,
            score: <%= @product_post.price_rate %>,
          });

           $('#star2-favorite_rate-<%= @product_post.id %>').raty({
           	size    : 36,
            starOff: '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            scoreName: 'product_post[favorite_rate]',
            readOnly: true,
            half: true,
            score: <%= @product_post.favorite_rate %>,
          });

           $('#star3-total_rate-<%= @product_post.id %>').raty({
           	size    : 36,
            starOff: '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            scoreName: 'product_post[total_rate]',
            readOnly: true,
            half: true,
            score: <%= @product_post.total_rate %>,
          });

           $('#star4').raty({
            size    : 36,
            starOff: '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            scoreName: 'product_comment[total_rate]',
            half: true,
          });
        </script>
        <!-- レビューのscriptここまで -->
      </div>
    </div>
  </div>
</div>