config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :customers, controllers: {
  	sessions:      'customers/sessions',
  	passwords:     'customers/passwords',
  	registrations: 'customers/registrations'
  }

  root 'home#top'
  get 'customers/about' => 'customers/home#about' #abouotページ
  get 'customers/contact' => 'customers/contacts#contact' #問合せフォーム
  post 'customers/confirm' => 'customers/contacts#confirm' #問合せ内容確認画面
  post 'customers/thanks' => 'customers/contacts#thanks' #問合せありがとうページ

  get 'customers/mypage' => 'customers#mypage' #myページ
  get 'customers/edit' => 'customers#edit' #パスワード編集ページ
  get 'customers/fix' => 'customers#fix' #編集ページ
  patch 'customers/fix' => 'customers#fix_update'
  put 'customers/fix' => 'customers#fix_update'
  get 'customers/withdraw' => 'customers#withdraw' #退会ページ
  put 'customers/withdraw' => 'customers#withdraw_update'

  get 'customers/cafe_posts/favorite' => 'customers/cafe_posts#favorite' #猫カフェ投稿いいね一覧
  get 'customers/product_posts/favorite' => 'customers/product_posts#favorite' #猫グッズ投稿いいね

  get 'customers/product_posts/mypost' => 'customers/product_posts#mypost' #自分の投稿
  get 'customers/product_posts/posts' => 'customers/product_posts#posts' #@customerの投稿

  post 'follow/:id' => 'customers/relationships#follow', as: 'follow' #フォローする
  delete 'unfollow/:id' => 'customers/relationships#unfollow', as: 'unfollow' #フォローを外す

# 　resources :customers, only: [:show, :index, :edit, :update] #フォロー
  get 'customers/:customer_id/followers' => 'customers/relationships#followers', as: 'followers'
  get 'customers/:customer_id/follows' => 'customers/relationships#follows', as: 'follows'

  get 'customers/search' => 'customers/product_posts#search' #postのsearch

  get 'customers/product_categories' => 'customers/product_categories#index' #カテゴリー一覧



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :customers do
  	resources :cafe_posts, only: [:index, :show, :update, :edit, :destroy, :create, :new] do #猫カフェ投稿
  	  resources :cafe_comments, only: [:create, :destroy] #猫カフェコメント
  	  resource :cafe_favorites, only: [:create, :destroy] #猫カフェいいね
  	end

  	resources :product_posts, only: [:index, :show, :update, :edit, :destroy, :create, :new] do #猫グッズ投稿
  	  resources :product_comments, only: [:create, :destroy] #猫グッズコメント
  	  resource :product_favorites, only: [:create, :destroy] #猫グッズいいね 
  	end

  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cafe_category.rb
class CafeCategory < ApplicationRecord
 has_many :cafe_posts
end

app/models/cafe_comment.rb
class CafeComment < ApplicationRecord
 belongs_to :customer
 belongs_to :cafe_post

validates :comment, presence: true
validates :total_rate, presence: true

 #一つの投稿に対して一人一つまでの投稿ができるメソッド
 def comment_already_posted?
  CafeComment.find_by(customer_id: self.customer_id, cafe_post_id: self.cafe_post_id).present?
 end
end

app/models/cafe_favorite.rb
class CafeFavorite < ApplicationRecord
 belongs_to :customer
 belongs_to :cafe_post
end

app/models/cafe_post.rb
class CafePost < ApplicationRecord
 belongs_to :customer
 belongs_to :cafe_category
 has_many :cafe_favorites
 has_many :cafe_comments
 # attachment :picture #画像投稿
 mount_uploader :picture, ImagesUploader

validates :shop_name, presence: true
validates :price, presence: true
validates :description, presence: true
validates :price_rate, presence: true
validates :free_rate, presence: true
validates :total_rate, presence: true

 def favorited_by?(customer) #因数で渡されたcustomer.idがfavoritesテーブル内に存在するかどうか
 	cafe_favorites.where(customer_id: customer.id).exists?
 end

 def CafePost.search(search, product_post_or_cafe_post)
  if product_post_or_cafe_post == "2"
     CafePost.where(['shop_name LIKE?', "%#{search}%"])
  else
     CafePost.all
   end
 end
end

app/models/contact.rb
class Contact < ApplicationRecord
 belongs_to :customer

validates :contact_name, presence: true
validates :contact_email, presence: true
validates :contact_content, presence: true
end

app/models/customer.rb
  class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #has_many :relationships, dependent: :destroy #カスタマーがDBから削除された場合、カスタマーが◯◯したものが全て消える
  has_many :cafe_favorites, dependent: :destroy
  has_many :cafe_posts, dependent: :destroy
  has_many :cafe_comments, dependent: :destroy
  has_many :product_favorites, dependent: :destroy
  has_many :favorite_products, through: :product_favorites, source: :product_post  # 孫要素の取得
  has_many :favorite_cafes, through: :cafe_favorites, source: :cafe_post  # 孫要素の取得
  has_many :product_posts, dependent: :destroy
  has_many :product_comments, dependent: :destroy
  has_many :contact

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy #フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy #フォロワー取得

  has_many :following_customer, through: :follower, source: :followed #自分がフォローしている人
  has_many :follower_customer, through: :followed, source: :follower #自分をフォローしている人

  # attachment :profile_image
  mount_uploader :profile_image, ImagesUploader


  validates :name, presence: true
  validates :tell, presence: true

#フォローする
 def follow(customer_id)
   follower.create(followed_id: customer_id)
 end

 #フォローを外す
 def unfollow(customer_id)
   follower.find_by(followed_id: customer_id).destroy
 end

 # フォローしていればtrueを返す
 def following?(customer)
  following_customer.include?(customer)
 end

end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
 has_many :product_posts
end

app/models/product_comment.rb
class ProductComment < ApplicationRecord
 belongs_to :customer
 belongs_to :product_post

 validates :comment, presence: true
 validates :total_rate, presence: true

 #一つの投稿に対して一人一つまでの投稿ができるメソッド
 def comment_already_posted?
  ProductComment.find_by(customer_id: self.customer_id, product_post_id: self.product_post_id).present?
 end
end

app/models/product_favorite.rb
class ProductFavorite < ApplicationRecord
 belongs_to :customer
 belongs_to :product_post
end

app/models/product_post.rb
class ProductPost < ApplicationRecord
 belongs_to :customer
 belongs_to :product_category
 has_many :product_favorites
 has_many :product_comments
 # attachment :picture #画像投稿
 mount_uploader :picture, ImagesUploader

 validates :product_name, presence: true
 validates :price, presence: true
 validates :description, presence: true
 validates :price_rate, presence: true
 validates :favorite_rate, presence: true
 validates :total_rate, presence: true

 def favorited_by?(customer) #因数で渡されたcustomer.idがfavoritesテーブル内に存在するかどうか
 	product_favorites.where(customer_id: customer.id).exists?
 end


  def ProductPost.search(search, product_post_or_cafe_post)
       if product_post_or_cafe_post == "1"
          ProductPost.where(['product_name LIKE?', "%#{search}%"])
      else
         ProductPost.all
       end
     end
  end

app/models/relationship.rb
class Relationship < ApplicationRecord
 belongs_to :follower, class_name: "Customer"
 belongs_to :followed, class_name: "Customer"
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/enum_helper.rb
module EnumHelper
  # クラスオブジェクトとカラム名を引数として呼ばれるコールバック関数です
  def options_for_select_from_enum(klass,column)
    #該当クラスのEnum型リストをハッシュで取得
    enum_list = klass.send(column.to_s.pluralize)
    #Enum型のハッシュリストに対して、nameと日本語化文字列の配列を取得（valueは使わないため_)
    enum_list.map do | name , _value |
      # selectで使うための組み合わせ順は[ 表示値, value値 ]のため以下の通り設定
      [ t("enums.#{klass.to_s.downcase}.#{column}.#{name}") , name ]
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse" >
  <div class="container-fluid">
    <div class="row fixed-top">
      <div class="col">
       <nav class="header">
        <div class="inner flex">
          <div class="logo">
            <%= link_to image_tag("miaou_5.jpg", size:'260x73'), "/" %>
          </div>
       <!-- </nav> -->
       <!-- <nav> -->
        <div class="menu1">
            <!-- ログインしている・しないない時のif文を加える -->
          <ul class="flex">
            <% if customer_signed_in? %>
                <li><%= link_to image_tag("headerabout.png", size:'100x80'), customers_about_path %></li>
                <li><%= link_to image_tag("headermy.png", size:'100x80'), customers_mypage_path %></li>
                <li><%= link_to image_tag("headergoods.png", size:'100x80'), customers_product_posts_path %></li>
                <li><%= link_to image_tag("headercafes.png", size:'100x80'), customers_cafe_posts_path %></li>
                <li><%= link_to image_tag("headerlogout.png", size:'100x80'), destroy_customer_session_path, method: :delete %></li>
            <% else %>
                <li><%= link_to image_tag("headerabout.png", size:'100x80'), customers_about_path %></li>
                <li><%= link_to image_tag("headersignup.png", size:'100x80'), "/customers/sign_up" %></li>
                <li><%= link_to image_tag("headerlogin.png", size:'100x80'), "/customers/sign_in" %></li>
            <% end %>


         </ul>
        </div>
        </div>
       </nav>
     </div>
    </div>
  </div>
 </header>

app/views/layouts/_sidebar.html.erb
<div class="col-2">
 <div class="sidebar">
   <h2>Category</h2>
    <p><i class="fas fa-paw"></i></p>

    <% @mixed_categories.each do |category| %>
    <div class="category_name"><a href="<%= customers_product_categories_path(id: category.id, type: category.class) %>"><%= category.category %></a></div>
    <% end %>
      <%= image_tag("linecat2.jpg", size:'150x80') %>
       <%= form_tag(customers_search_path, :method => 'get') do %>
        <%= select_tag(:option, options_for_select([["猫グッズ","1"],["猫カフェ","2"]]),id:"sidebar_option") %>
        <%= text_field_tag :search,"",id:'sidebar_search' %>
        <%= submit_tag 'Search',class:"button" %><br>
       <% end %>
         <br><p><i class="fas fa-paw"></i></p>
         <p><%= link_to "お問い合わせ", customers_contact_path %></p>

       <div class="menu">
          <label class="side" for="menu_bar01">猫カフェ</label>
           <input type="checkbox" id="menu_bar01" class="accordion"/>
         <ul id="links01">
          <li><a href="/customers/cafe_posts/"><i class="far fa-comments"></i>投稿を見る</a></li>
          <li><a href="/customers/cafe_posts/new"><i class="fas fa-pencil-alt"></i>投稿する</a></li>
          <li><a href="/customers/cafe_posts/favorite"><i class="fas fa-heart"></i>お気に入り</a></li>
         </ul>
          <label class="side" for="menu_bar02">猫グッズ</label>
          <input type="checkbox" id="menu_bar02" class="accordion"/>
         <ul id="links02">
          <li><a href="/customers/product_posts/"><i class="far fa-comments"></i>投稿を見る</a></li>
          <li><a href="/customers/product_posts/new"><i class="fas fa-pencil-alt"></i>投稿する</a></li>
          <li><a href="/customers/product_posts/favorite"><i class="fas fa-heart"></i>お気に入り</a></li>
         </ul>
        </div>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiaouMiaou</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <body>
   <div id="wrapper">

        <%= render 'layouts/header' %>

    <div class="main">
        <%= yield %>
    </div>

    <footer>
        <p class="text-muted"> ©︎2020 Miaou!Miaou! </p>
    </footer>

   </div>
   <div id="page_top"><%= image_tag("pagetop2.png", size:'170x250') %></div>
  </body>
</html>